import { FileText } from "lucide-react";

const SessionsContent = () => (
  <div className="space-y-6">
    <div className="bg-white p-6 rounded-lg border border-gray-200 shadow-sm">
      <h2 className="text-2xl font-semibold text-gray-800 mb-4 flex items-center">
        <FileText className="w-6 h-6 mr-2 text-green-600" />
        Session Details
      </h2>
      <div className="space-y-6">
        {[
          {
            speaker: "Dr. Syed Ashraf Uddin",
            title: "Supernova Cosmology",
            overview:
              "Type Ia Supernovae (SNe Ia) are standardizable candles to measure distances across the Universe. While the use of SNe Ia has led to the surprising discovery of cosmic acceleration, the nature of dark energy remains elusive. In this session I will walk you through the fundamentals of supernova cosmology and how we use SNe Ia to derive cosmological parameters. The session will include SNe Ia light-curve and spectral analysis and Bayesian likelihood analysis.",
          },
          {
            speaker: "Dr. Tonima Tasnim Ananna",
            title: "How astronomers today find exciting cosmic phenomena",
            overview:
              "How to catch a star? Ever wonder how astrophysicists can tell when two black holes collide? Or when a star blows up? Or how the space near a black hole is curved by the gargantuan gravitational force generated by a black hole? Or what the early Universe looked like? In this lecture, we are going to cover all the most exciting detections designed by physicists to detect paradigm-shifting physical phenomena in the last century.",
          },
          {
            speaker: "Dr. Syeda Lammim Ahad",
            title: "The Largest Structures in the Universe",
            overview:
              "What are the largest structures in the Universe? Why are they interesting to study and understand? What are they made of? In this lecture, we will explore these questions and learn how astronomers study some of the most interesting features of these systems.",
            exercise: "",
          },
          {
            speaker: "Dr. Tabassum Shahriar Tanvir",
            title: "Star formation",
            overview: "TBA",
          },
          {
            speaker: "Ahmad Al-Imtiaz",
            title:
              "NIRSpec (JWST) Data Reduction: From Archive to Science-Ready Spectra",
            overview:
              "In this session, participants will be introduced to the process of reducing spectroscopic data obtained with the Near Infrared Spectrograph (NIRSpec) aboard the James Webb Space Telescope (JWST). We will begin by retrieving Stage II calibrated data from the MAST (Mikulski Archive for Space Telescopes) archive for a selected science target. By the end of the session, participants will have a clear understanding of how to handle NIRSpec data for their own research—transforming raw archival observations into clean, science-ready spectra for further astrophysical analysis.",
          },
          {
            speaker: "K M Shariat Ullah",
            title: "Simulating the Early Universe using 21cmFAST",
            overview:
              "In this session, participants will explore the theoretical foundations of 21 cm cosmology and the Epoch of Reionization focusing on how the universe transitioned from a neutral to an ionized state. Using the semi-numerical simulation tool 21cmFAST, they will investigate the impact of varying key cosmological parameters, such as the Hubble parameter H(t) and dark matter density Ωm on the ionization of neutral hydrogen. Through hands-on experience simulating the universe, participants will develop a clear understanding of how the early universe has evolved.",
          },
          {
            speaker: "Tanmoy Bhowmik",
            title:
              "Galaxy SED Fitting: From Photometric Data to Physical Parameter Modeling",
            overview:
              "Galaxy spectral energy distributions (SEDs) fitting is a technique in astrophysics used to model the observed fluxes of galaxies across different wavelengths, enabling astronomers to infer physical properties such as star formation history, dust content, and metallicity. This hands-on session introduces participants to the essential steps involved in modeling and fitting galaxy SEDs. Participants will learn how to load and inspect photometric observational data, and how to fit observational SEDs with theoretical models to estimate key galaxy parameters. They will work with both real and simulated data using Python notebooks to gain a practical understanding of how galaxy properties can be derived through SED fitting techniques.",
          },
        ].map((session, index) => (
          <div
            key={index}
            className="border border-gray-200 rounded-lg p-6 bg-gray-50"
          >
            <h3 className="text-lg font-semibold text-gray-800 mb-2">
              {session.speaker}
            </h3>
            <h4 className="text-md font-medium text-blue-600 mb-3">
              {session.title}
            </h4>
            <p className="text-gray-700 text-sm leading-relaxed mb-3">
              {session.overview}
            </p>
            {session.exercise && (
              <div className="bg-yellow-50 border border-yellow-200 rounded p-3 mt-3">
                <h5 className="font-semibold text-gray-800 mb-1">Exercise:</h5>
                <p className="text-sm text-gray-700">{session.exercise}</p>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  </div>
);

export default SessionsContent;
